### ISSUE TITLE
Unable to use an exact version

### ISSUE THREAD

**Issue by MohamedXi** [LiYanan2004/MarkdownView#5] opened 2023-05-05 09:01 UTC
I can't seem to use an exact version of the package.
Is this normal?

**Comment by louis49** [comment] 2023-05-05 09:13
When fixing version with 1.1.0, Xcode says : "Failed to resolve dependencies Dependencies could not be resolved because package 'markdownview' is required using a stable-version but 'markdownview' depends on an unstable-version package 'swift-markdown' and root depends on 'markdownview' 1.1.0."

**Comment by LiYanan2004** [comment] 2023-05-05 09:24
I'm sorry. It's normal upon till now. 

This framework depends on Apple's swift-markdown framework, and maybe that framework is still in progress. I can't specify a constant tag because there might have some bugs inside the package.

To solve that, you just need to **switch to my main branch** to get the latest update. And don't worry, I will only merge stable version of MarkdownView to main branch.

**Comment by LiYanan2004** [comment] 2023-05-05 09:28
If you use Xcode to add this package, choose Dependency Rule to Branch and main.
![](https://user-images.githubusercontent.com/80188597/231553796-a9ab252a-ea47-4f7a-9790-171807866cf5.jpeg)

**Comment by LiYanan2004** [comment] 2023-05-05 09:32
@louis49 I've seen your PR. I'll check this out. Thanks.

**Comment by louis49** [comment] 2023-05-05 09:42
Thank you a lot. Can you create a new release with this fix please ?

**Comment by LiYanan2004** [comment] 2023-05-05 09:42
OK. I'll do that soon.

**Comment by LiYanan2004** [comment] 2023-05-05 09:51
@louis49 Published and @MohamedXi You can try it again. Enjoy it.

**Comment by LiYanan2004** [comment] 2023-05-05 09:59
@louis49 Seems like it's still not fixed because we use 'branch' dependency and there might have future pushes. (It's not a static release or static tag).

**Comment by LiYanan2004** [comment] 2023-05-05 10:01
I reopened this issue because it's not fixed and maybe this won't and can't be fixed in recent.

**Closed** 2023-05-05 10:08 UTC

**Comment by louis49** [comment] 2023-05-05 11:57
You can get the same result by letting "main" in "main" branch and "release/5.8" in a tagged version ...

**Comment by LiYanan2004** [comment] 2023-05-05 12:14
@louis49 As you mentioned, same result.

> When fixing version with 1.1.0, Xcode says : "Failed to resolve dependencies Dependencies could not be resolved because package 'markdownview' is required using a stable-version but 'markdownview' depends on an unstable-version package 'swift-markdown' and root depends on 'markdownview' 1.1.0."

This issue remains. It doesn’t make sense. The only solution here is directly use main branch

**Comment by louis49** [comment] 2023-05-05 12:28
I think you can do : 
* Merge my PR
* Create a new release with a tag with that code
* Roll-back the dependency version of swift-markdown.git to "main"
* Push this to your main branch

=> Your main branch will work with all new fixes of swift markdown : you are happy ! 
=> 1.2.0 tag will keep current code fixed : I am happy ! 

;-)

**Comment by LiYanan2004** [comment] 2023-05-05 14:00
@louis49 I understand your requirement, but I’m wondering why you need that fix? I tested, still says “failed to resolve …”

**Comment by Kyle-Ye** [comment] 2023-05-21 05:56
The problem is if you use a branch dependency in the Package.swift file. There is no meaning publishing a version for it since SwiftPM will reject to use it.

A fixed commit revision dependency to swift-markdown may help solve the problem.

**Comment by LiYanan2004** [comment] 2023-05-21 06:26
> The problem is if you use a branch dependency in the Package.swift file. There is no meaning publishing a version for it since SwiftPM will reject to use it.
> 
> A fixed commit revision dependency to swift-markdown may help solve the problem.

Yes. I must switch to a fixed **commit**, but #6 is trying to use a branch, which results in the same error.

**Comment by LiYanan2004** [comment] 2023-05-27 03:58
`swift-markdown` has a official release now. I have updated my package. Fixed now. @MohamedXi @louis49 Check it out.

**Comment by louis49** [comment] 2023-06-05 05:18
Thank you
